sonar.host.url=https://sonar.iduart.es

sonar.token=squ_04444d82cdcd2a4cbe4450077dee59d4edcbca5b
sonar.projectKey=com.carajillolabs:sif-web
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/.angular/**
sonar.sources=src
sonar.organization=carajillolabs
