// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _dashboard_calendar from './dashboard-calendar.bones.json'
import _dashboard_today_list from './dashboard-today-list.bones.json'
import _menus_list from './menus-list.bones.json'
import _templates_list from './templates-list.bones.json'
import _appointments_calendar from './appointments-calendar.bones.json'
import _appointments_today_list from './appointments-today-list.bones.json'
import _user_detail_header from './user-detail-header.bones.json'
import _menu_detail_content from './menu-detail-content.bones.json'
import _template_detail_content from './template-detail-content.bones.json'
import _patients_list from './patients-list.bones.json'
import _staff_list from './staff-list.bones.json'

registerBones({
  "dashboard-calendar": _dashboard_calendar,
  "dashboard-today-list": _dashboard_today_list,
  "menus-list": _menus_list,
  "templates-list": _templates_list,
  "appointments-calendar": _appointments_calendar,
  "appointments-today-list": _appointments_today_list,
  "user-detail-header": _user_detail_header,
  "menu-detail-content": _menu_detail_content,
  "template-detail-content": _template_detail_content,
  "patients-list": _patients_list,
  "staff-list": _staff_list,
})
